# Generated by Django 3.1 on 2021-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210604_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desciption',
            field=models.TextField(default='This is a test description'),
            preserve_default=False,
        ),
    ]
